# -*- coding: utf-8 -*-
"""cad_com_arq_v3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YaTp4sYBFjjSS4Yn2wo_IUj326prlkqg
"""

# Função Principal

def pessoas(arq):
  opcao = menu()
  while opcao != 3:
    if opcao == 2:
      while True:
        cadastrar(arq, nome(), idade())
        continuar = SoN('Deseja adcionar mais uma pessoa? ')
        if continuar == 'N':
          break
      opcao = menu()
    if opcao == 1:
      LerArquivo(arq)
      opcao = menu()
  if opcao == 3:
    printcolorido('Programa finalizado.','azul')


# Módulos Auxiliares

def cadastrar(arq, nome='desconhecido', idade=0):
  try:
    a = open(f'/content/{arq}', 'at')
  except:
    printcolorido('Houve um ERRO ao abrir o arquivo.','vermelho')
  else:
    try:
      a.write(f'{nome};{idade}\n')
    except:
      printcolorido('Houve um ERRO ao adcionar os dados.','vermelho')
    else:
      printcolorido(f'Os dados de {nome} foram adcionados.','verde')
  finally:
    a.close()

def ArquivoExiste(arq):
  try:
    a = open(f'/content/{arq}', 'rt')
  except FileNotFoundError:
    return False
  else:
    return True
  finally:
    a.close()

def CriarArquivo(arq):
  try:
    a = open(f'/content/{arq}', 'wt+')
  except:
    printcolorido('Hoube um ERRO na criação do arquivo.','vermelho')
  else:
    printcolorido(f'Arquivo {arq} criado com sucesso.','verde')
  finally:
    a.close()

def LerArquivo(arq):
  try:
    a = open(f'/content/{arq}','rt')
  except:
    printcolorido('Erro ao ler o arquivo.','vermelho')
  else:
      print('-'*40)
      print(f'{"PESSOAS CADASTRADAS":^40}')
      print('-'*40)
      for l in a:
        dado = l.split(';')
        dado[1] = dado[1].replace('\n','')
        print(f'{dado[0]:<30}{dado[1]+" anos":^10}')
  finally:
    a.close()

def txtcolorido(msg='Sem Mensagem',cor='branco',est='normal'):
  cor = cor.lower()
  est = est.lower()
  if est == 'normal':
      est = ';0'
  elif est == 'negrito':
      est = ';1'
  elif est == 'itálico':
      est = ';3'
  elif est == 'sublinhado':
      est = ';4'
  else:
      est = ';0'

  if cor == 'cinza':
    return f'\033[30{est}m{msg}\033[0m'
  elif cor == 'vermelho':
    return f'\033[31{est}m{msg}\033[0m'
  elif cor == 'verde':
    return f'\033[32{est}m{msg}\033[0m'
  elif cor == 'amarelo':
    return f'\033[33{est}m{msg}\033[0m'
  elif cor == 'azul':
    return f'\033[34{est}m{msg}\033[0m'
  elif cor == 'rosa':
    return f'\033[35{est}m{msg}\033[0m'
  elif cor == 'ciano':
    return f'\033[36{est}m{msg}\033[0m'
  elif cor == 'branco':
    return f'\033[{est}m{msg}\033[0m'
  else:
    return 'Cor inválida.'
    
def printcolorido(msg='Sem Mensagem',cor='branco'):
  cor = cor.lower()
  if cor == 'cinza':
    print(f"\033[30m{msg}\033[0m")
  elif cor == 'vermelho':
    print(f"\033[31m{msg}\033[0m")
  elif cor == 'verde':
    print(f"\033[32m{msg}\033[0m")
  elif cor == 'amarelo':
    print(f"\033[33m{msg}\033[0m")
  elif cor == 'azul':
    print(f"\033[34m{msg}\033[0m")
  elif cor == 'rosa':
    print(f"\033[35m{msg}\033[0m")
  elif cor == 'ciano':
    print(f"\033[36m{msg}\033[0m")
  elif cor == 'branco':
    print({msg})
  else:
    print('#Cor_inválida#')
  
def menu():
  print('-'*40)
  print(f'{"MENU PRINCIPAL":^40}')
  print('-'*40)
  print('\033[32;1m1\033[0m - Ver pessoas cadastradas.')
  print('\033[32;1m2\033[0m - Cadastrar nova pessoa.')
  print('\033[32;1m3\033[0m - Sair.')
  print('-'*40)
  while True:
    opcao = input('Digite sua opção: ')
    if opcao == '1' or opcao == '2' or opcao == '3':
      return int(opcao)
    else:
      printcolorido('Opção inválida, tente novamente.', 'Vermelho')

def nome():
  while True:
    nome = input('Nome: ').title()
    nome = ' '.join(nome.split())
    if nome.replace(' ','').isalpha():
      return nome
    printcolorido('Digite um nome válido.','vermelho')

def idade():
  while True:
    idade = input('Idade: ').replace(' ','')
    try:
      int(idade)
      return int(idade)
    except:
      printcolorido('Digite uma idade válida.','vermelho')

def SoN(msg):
  while True:
    op = input(msg).upper()[0]
    if op == 'S':
      return op
    elif op == 'N':
      return op
    else:
      printcolorido("Digite Sim ou Não.",'vermelho')