# -*- coding: utf-8 -*-
"""cadastro

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JbcAK-6rYXAeqzlVQVxafIULF3RWeAOc
"""

# Função Principal

def pessoas():
  dicio, lista = {}, []
  opcao = menu()
  while opcao != 3:
    if opcao == 2:
      while True:
        dicio['nome'] = nome()
        dicio['idade'] = idade()
        lista.append(dicio.copy())
        dicio.clear()
        continuar = SoN('Deseja adcionar mais uma pessoa? ')
        if continuar == 'N':
          break
      opcao = menu()
    if opcao == 1:
      print('-'*40)
      print(f'{"PESSOAS CADASTRADAS":^40}')
      print('-'*40)
      for p in lista:
        print(f'{p["nome"]:<30}{(str(p["idade"])+" anos"):^10}')
      opcao = menu()
  if opcao == 3:
    printcolorido('Programa finalizado.','azul')


# Módulos Auxiliares

def txtcolorido(msg='Sem Mensagem',cor='branco',est='normal'):
  cor = cor.lower()
  est = est.lower()
  if est == 'normal':
      est = ';0'
  elif est == 'negrito':
      est = ';1'
  elif est == 'itálico':
      est = ';3'
  elif est == 'sublinhado':
      est = ';4'
  else:
      est = ';0'

  if cor == 'cinza':
    return f'\033[30{est}m{msg}\033[0m'
  elif cor == 'vermelho':
    return f'\033[31{est}m{msg}\033[0m'
  elif cor == 'verde':
    return f'\033[32{est}m{msg}\033[0m'
  elif cor == 'amarelo':
    return f'\033[33{est}m{msg}\033[0m'
  elif cor == 'azul':
    return f'\033[34{est}m{msg}\033[0m'
  elif cor == 'rosa':
    return f'\033[35{est}m{msg}\033[0m'
  elif cor == 'ciano':
    return f'\033[36{est}m{msg}\033[0m'
  elif cor == 'branco':
    return f'\033[{est}m{msg}\033[0m'
  else:
    return 'Cor inválida.'
    
def printcolorido(msg='Sem Mensagem',cor='branco'):
  cor = cor.lower()
  if cor == 'cinza':
    print(f'\033[30m{msg}\033[0m')
  elif cor == 'vermelho':
    print(f'\033[31m{msg}\033[0m')
  elif cor == 'verde':
    print(f'\033[32m{msg}\033[0m')
  elif cor == 'amarelo':
    print(f'\033[33m{msg}\033[0m')
  elif cor == 'azul':
    print(f'\033[34m{msg}\033[0m')
  elif cor == 'rosa':
    print(f'\033[35m{msg}\033[0m')
  elif cor == 'ciano':
    print(f'\033[36m{msg}\033[0m')
  elif cor == 'branco':
    print({msg})
  else:
    print('Cor inválida.')
  
def menu():
  print('-'*40)
  print(f'{"MENU PRINCIPAL":^40}')
  print('-'*40)
  print('\033[32;1m1\033[0m - Ver pessoas cadastradas.')
  print('\033[32;1m2\033[0m - Cadastrar nova pessoa.')
  print('\033[32;1m3\033[0m - Sair.')
  print('-'*40)
  while True:
    opcao = input('Digite sua opção: ')
    if opcao == '1' or opcao == '2' or opcao == '3':
      return int(opcao)
    else:
      printcolorido('Opção inválida, tente novamente.', 'Vermelho')

def nome():
  while True:
    nome = input('Nome: ').title()
    nome = ' '.join(nome.split())
    if nome.replace(' ','').isalpha():
      return nome
    printcolorido('Digite um nome válido.','vermelho')

def idade():
  while True:
    idade = input('Idade: ').replace(' ','')
    try:
      int(idade)
      return int(idade)
    except:
      printcolorido('Digite uma idade válida.','vermelho')

def SoN(msg):
  while True:
    op = input(msg).upper()[0]
    if op == 'S':
      return op
    elif op == 'N':
      return op
    else:
      printcolorido("Digite Sim ou Não.",'vermelho')