# -*- coding: utf-8 -*-
"""leia

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yHbiPyEgzcqIavH5gwokpLAaxK2rcm2H
"""

def dinheiro(msg):
  válido = False
  while not válido:
    entrada = input(msg).replace(',','.').replace(' ','')
    if entrada.isalpha() or entrada == '':
      print(f'"{entrada}" é um preço inválido.')
    else:
      válido = True
      return float(entrada)

def numint(msg):
  while True:
    n = input(msg).replace(',','.').replace(' ','')
    try:
        int(n)
        return int(n)
    except:
      print(f'Você não digitou um número inteiro.')

def numfloat(msg):
  while True:
    n = input(msg).replace(',','.').replace(' ','')
    try:
        float(n)
        return float(n)
    except:
      print(f'Você não digitou um número real.')