# -*- coding: utf-8 -*-
"""moeda

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SEerTNOcWPyP8AMqKlPIQMpSdU7WjCr-
"""

def aumento(n=0,t=0,format=True):
  res = n*(100 + t)/100
  if format == True: return dinheiro(res)
  else: return res

def desconto(n=0,t=0,format=True):
  res = n*(100 - t)/100
  if format == True: return dinheiro(res)
  else: return res

def metade(n=0,format=True):
  res = n/2
  if format == True: return dinheiro(res)
  else: return res

def dobro(n=0,format=True):
  res = n*2
  if format == True: return dinheiro(res)
  else: return res

def dinheiro(preco=0,moeda='R$'):
  return str(f'{moeda}{preco:.2f}'.replace('.',','))

def resumo(preco=0,des=0,aum=0):
  print('-'*30)
  print(f"{'RESUMO DO VALOR':^30}")
  print('-'*30)
  print(f"{'Preço analisado:':<20}{dinheiro(preco)}")
  print(f"{'Dobro do preço:':<20}{dobro(preco)}")
  print(f"{'Metade do preço:':<20}{metade(preco)}")
  print(f"{str(aum)+'% de aumento:':<20}{aumento(preco,aum)}")
  print(f"{str(des)+'% de desconto:':<20}{desconto(preco,des)}")
  print('-'*30)