# -*- coding: utf-8 -*-
"""operações

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VrEWLuLda06tXtL8qufiB22zyibeSHcH
"""

def fatorial(n):
  f = 1
  for c in range(n,0,-1):
    f = f*c
  return f

def soma(*n):
  s = sum(n)
  return s

def produto(*n):
  p = 1
  for c in n:
    p *= c
  return p

def raizquad(n):
  return n**(1/2)


if __name__ == '__main__':
  print(fatorial(4))
  print(soma(5,3,2))
  print(produto(3,5))
  print(raizquad(4))
